<script setup>
import LaundryLayout from '@/Layouts/Staff/LaundryLayout.vue'
import { usePage } from '@inertiajs/vue3'
import { Printer, Receipt, Hash, DoorOpen } from 'lucide-vue-next'

const page = usePage();
const props = defineProps({ order: Object });
const siteName = page.props.settings?.site_name || 'HotelMS';

const printOrder = () => {
  window.print();
};
</script>

<template>
  <LaundryLayout>
    <div class="max-w-2xl mx-auto px-4 py-8">
      <div class="mb-6 flex justify-between items-center print:hidden">
        <button 
          @click="$router.back()" 
          class="text-slate-500 font-bold text-sm hover:text-slate-800 transition-colors"
        >
          ← Back to Dashboard
        </button>
        <button 
          @click="printOrder" 
          class="inline-flex items-center gap-2 px-6 py-2.5 bg-slate-900 text-white rounded-xl font-bold hover:bg-indigo-600 transition-all shadow-lg shadow-slate-200 active:scale-95"
        >
          <Printer class="w-4 h-4" />
          Print Receipt
        </button>
      </div>

      <div class="bg-white border border-slate-200 rounded-[2.5rem] shadow-sm overflow-hidden print:border-none print:shadow-none print:rounded-none">
        <div class="bg-slate-50/50 p-8 border-b border-slate-100 text-center relative overflow-hidden">
          <div class="relative z-10 flex flex-col items-center">
            <div class="w-16 h-16 bg-white rounded-2xl shadow-sm border border-slate-100 flex items-center justify-center mb-4">
              <Receipt class="w-8 h-8 text-indigo-600" />
            </div>
            <h1 class="text-2xl font-black text-slate-900 uppercase tracking-tighter">Laundry Invoice</h1>
            <div class="mt-2 flex items-center gap-4 text-slate-500 font-bold text-xs uppercase tracking-widest">
              <span class="flex items-center gap-1"><Hash class="w-3 h-3" /> {{ order.order_code }}</span>
              <span class="flex items-center gap-1"><DoorOpen class="w-3 h-3" /> Room {{ order.room.name }}</span>
            </div>
          </div>
          <div class="absolute -top-10 -right-10 w-32 h-32 bg-indigo-50 rounded-full opacity-50"></div>
        </div>

        <div class="p-8">
          <table class="w-full text-left">
            <thead>
              <tr class="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] border-b border-slate-100">
                <th class="pb-4">Item Description</th>
                <th class="pb-4 text-center">Qty</th>
                <th class="pb-4 text-right">Subtotal</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-50">
              <tr v-for="i in order.items" :key="i.id" class="text-slate-700">
                <td class="py-4 font-bold text-sm">{{ i.item.name }}</td>
                <td class="py-4 text-center font-medium text-slate-500">{{ i.quantity }}</td>
                <td class="py-4 text-right font-black text-slate-900">₦{{ i.subtotal }}</td>
              </tr>
            </tbody>
            <tfoot>
              <tr class="border-t-2 border-slate-900">
                <td colspan="2" class="pt-6 text-sm font-black text-slate-900 uppercase tracking-wider">Total Amount Due</td>
                <td class="pt-6 text-right text-2xl font-black text-indigo-600">₦{{ order.total_amount }}</td>
              </tr>
            </tfoot>
          </table>

          <div class="mt-12 pt-8 border-t border-dashed border-slate-200 text-center">
            <p class="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">Generated by {{ siteName }} Staff Portal</p>
            <p class="text-[10px] text-slate-300">{{ new Date().toLocaleString() }}</p>
          </div>
        </div>
      </div>

      <div class="flex justify-between px-4 opacity-10 print:hidden">
        <div v-for="i in 12" :key="i" class="w-4 h-4 bg-slate-400 rounded-full -mt-2"></div>
      </div>
    </div>
  </LaundryLayout>
</template>

<style scoped>
@media print {
  /* Ensure the background and indigo colors print correctly */
  body {
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  
  /* Reset margins for printing */
  @page {
    margin: 1cm;
  }

  /* Hide UI elements */
  .LaundryLayout :deep(aside), 
  .LaundryLayout :deep(header),
  .print\:hidden {
    display: none !important;
  }

  .LaundryLayout :deep(main) {
    padding: 0 !important;
    background: white !important;
  }
}

/* Scoped scannability for the table */
table {
  border-collapse: collapse;
}
</style>