[program:hotelms-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/u776774917/domains/mooreliferesort.com/Hotelms/artisan queue:work --sleep=3 --tries=3 --max-time=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=u776774917
numprocs=2
stdout_logfile=/home/u776774917/domains/mooreliferesort.com/Hotelms/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/home/u776774917/domains/mooreliferesort.com/Hotelms/storage/logs/worker-error.log
stderr_logfile_maxbytes=10MB